### ISSUE TITLE
Would it be possible to publish flex/yacc source files?

### ISSUE THREAD

**Issue by ppiecuch** [BobLChen/ShaderLab#1]
Great piece of code! I would like to add support for some other ShaderLab statements like [Toggle], but that require more source files :) Any chance for adding these ?

Regards
Pawel

**Comment by BobLChen** [comment]
Ok！No problem.

**Comment by BobLChen** [comment]
@ppiecuch 3abfef710248bd38f69aefd3b7b992603128ac27

**Comment by ppiecuch** [comment]
Thx! :)
